{% set version = "1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-quarto
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/quarto_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/quarto/quarto_{{ version }}.tar.gz
  sha256: 699cf5a68a8dd011acc2f998742539acbc20305655c1edcc848d7228f201d8a0

build:
  merge_build_host: true  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - quarto
    - r-base
    - r-jsonlite
    - r-later
    - r-processx
    - r-rmarkdown
    - r-rsconnect >=0.8.26
    - r-rstudioapi
    - r-yaml
  run:
    - quarto
    - r-base
    - r-jsonlite
    - r-later
    - r-processx
    - r-rmarkdown
    - r-rsconnect >=0.8.26
    - r-rstudioapi
    - r-yaml

test:
  requires:
    - r-testthat >=3.1.0
  commands:
    - $R -e "library('quarto')"                 # [not win]
    - $R -e "testthat::test_package('quarto')"  # [not win]
    - "\"%R%\" -e \"library('quarto')\""                 # [win]
    - "\"%R%\" -e \"testthat::test_package('quarto')\""  # [win]

about:
  home: https://github.com/quarto-dev/quarto-r
  license: GPL-2.0-or-later
  summary: Convert R Markdown documents and 'Jupyter' notebooks to a variety of output formats using 'Quarto'.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
